require('mason-lspconfig').setup {
    automatic_enable = true,
    -- https://mason-registry.dev/registry/list
    ensure_installed = {
        "bashls",
        "docker_compose_language_service",
        "dockerls",
        "eslint",
        "graphql",
        "html",
        "jsonls",
        "lua_ls",
        "pyright",
        "ruff",
        "sqlls",
        "stylelint_lsp",
        "ts_ls",
        "yamlls",
        "tflint",
        "terraformls",
        "postgres_lsp",
        "harper_ls",
        "nginx_language_server",
        "gh_actions_ls",
    },
}
