require('mason-lspconfig').setup {
    automatic_enable = false,
    ensure_installed = {
        "bashls",
        "docker_compose_language_service",
        "dockerls",
        "eslint",
        "graphql",
        "html",
        "jsonls",
        "lua_ls",
        "pyright",
        "sqlls",
        "stylelint_lsp",
        "ts_ls",
        "yamlls",
        "tflint",
        "terraformls",
        "postgres_lsp",
        "harper_ls",
    },
}
