#!/bin/bash
# Warn before pushing to protected branches
# Make script executable with chmod +x pre-push
# Bypass with git push --no-verify

# git lfs
# Only run the git-lfs pre-push when git-lfs is actually used in this repo
if git grep -q filter=lfs -- .gitattributes '**/.gitattributes' # https://stackoverflow.com/a/76197696
then
    command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path.\n"; exit 2; }
    git lfs post-merge "$@"
fi

# Run from active git repo
set -eu
hook_name="$(basename "$0")"
hook_script="$(git rev-parse --git-common-dir)/hooks/$hook_name"
[ -e "$hook_script" ] && "$hook_script"
exit 0
