# https://phelipetls.github.io/posts/introduction-to-ansible/
# https://www.reddit.com/r/archlinux/comments/y5e6wy/learned_bit_of_ansible_to_automate_some/
# https://github.com/DoTheEvo/ansible-arch/blob/main/playbook_zsh.yml
---
- name: Archlinux base setup - During install only
  hosts: localhost
  become: true

  vars_files:
    - ../local.yml

  vars_prompt:
    - name: new_password
      prompt: What is your password?
      private: true
      encrypt: sha512_crypt
      confirm: true
      salt_size: 7

  tasks:
    - ansible.builtin.import_role:
        name: bootstrap

    - ansible.builtin.import_role:
        name: pacman

    - ansible.builtin.import_role:
        name: users

    - ansible.builtin.import_role:
        name: bootloader

    - ansible.builtin.import_role:
        name: network

    - ansible.builtin.import_role:
        name: dns
