---
- name: Archlinux sync configuration from all playbooks (except init.yml)
  hosts: localhost

- import_playbook: ./system-config.yml
- import_playbook: ./system-packages.yml
- import_playbook: ./system-aur-config.yml
- import_playbook: ./amd-gpu-config.yml
