# https://wiki.archlinux.org/title/Zram
# https://aur.archlinux.org/packages/zramswap
---
- name: Archlinux system swap configuration
  hosts: localhost
  become: true

  tasks:
    - name: enable zramswap
      systemd:
        name: zramswap.service
        enabled: yes
        state: started
