---
- name: Install packages with uv tool install
  ansible.builtin.shell: |
    uv tool install --no-progress {{ item }}
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.HOME }}/.local/bin/{{ item }}"
  loop: "{{ uv_tools }}"
