# https://phelipetls.github.io/posts/introduction-to-ansible/
# https://www.reddit.com/r/archlinux/comments/y5e6wy/learned_bit_of_ansible_to_automate_some/
# https://github.com/DoTheEvo/ansible-arch/blob/main/playbook_zsh.yml
---
- name: playbook_core.yml - archlinux base setup
  hosts: localhost
  become: yes
  vars_prompt:
    - name: new_hostname
      prompt: What is your hostname?
      private: false
    - name: new_username
      prompt: What is your username?
      private: false
    - name: new_password
      prompt: What is your password?
      private: true
      encrypt: sha512_crypt
      confirm: true
      salt_size: 7

  tasks:
    # Arch install setups --AFTER CHROOT--------------------------------------
    # https://wiki.archlinux.org/title/installation_guide#Configure_the_system
    - name: Set timezone (Asia/Kathmandu)
      ansible.builtin.file:
        src: /usr/share/zoneinfo/Asia/Kathmandu
        dest: /etc/localtime
        owner: root
        group: root
        state: link

    - name: Update hardware clock
      ansible.builtin.command: hwclock --systohc

    # -- Locale
    - name: Enable en_US locale
      lineinfile:
        path: /etc/locale.gen
        regexp: '^#en_US.UTF-8 UTF-8$'
        line: 'en_US.UTF-8 UTF-8'

    - name: Generate locale
      ansible.builtin.command: locale-gen

    - name: Create /etc/locale.conf
      blockinfile:
        path: /etc/locale.conf
        state: present
        create: yes
        block: LANG=en_US.UTF-8

    - name: Set hostname
      copy:
        dest: /etc/hostname
        content: "{{ new_hostname }}"

    # System packages
    - name: Arch Full Update
      become: yes
      pacman:
        update_cache: yes
        upgrade: yes

    # USERS PERMISSIONS  ---------------------------------------------------------
    - name: install sudo & zsh
      pacman:
        name:
          - sudo
          - zsh

    - name: Create new user with "{{ new_username }}"
      user:
        name: "{{ new_username }}"
        password: "{{ new_password }}"
        shell: /bin/zsh
        create_home: true

    - name: Set same password for root
      user:
        name: "root"
        password: "{{ new_password }}"

    - name: enable members of wheel group to sudo
      lineinfile:
        path: /etc/sudoers.d/01_wheel_allow_sudo
        state: present
        line: "%wheel ALL=(ALL:ALL) ALL"
        validate: /usr/sbin/visudo -cf %s
        create: yes

    - name: add the user to the wheel group
      user:
        name: "{{ new_username }}"
        groups: wheel
        append: yes

    # GRUB Setup -----------------------------------------------------------------
    - name: Install Grub
      pacman:
        name:
          - grub
          - efibootmgr

    - name: Grub bootloader install
      ansible.builtin.command: |
        grub-install \
          --target=x86_64-efi \
          --efi-directory=/boot/ \
          --bootloader-id=GRUB

    - name: Update grub timeout to 1
      lineinfile:
        path: /etc/locale.gen
        regexp: '^GRUB_TIMEOUT=5$'
        line: 'GRUB_TIMEOUT=1'

    - name: Generate grub config
      ansible.builtin.command: grub-mkconfig -o /boot/grub/grub.cfg
