#!/bin/zsh -e

# function tsh_login_using_1password() {
#     tsh status &>/dev/null || {
#         spawn tsh login --proxy=$TSH_PROXY --user=$TSH_USER --mfa-mode=$TSH_MFA_MODE
#         expect -re "Enter password for Teleport user $USERNAME*" {
#             send -- "$(op read \"$OP_TSH_USERNAME/password\")\n"
#             interact
#         }
#         expect -re "Enter an OTP code from a device:" {
#             send -- "$(op read \"$OP_TSH_USERNAME/one-time password?attribute=otp\")\n"
#             interact
#         }
#     }
# }


function tsh_login() {
    if [[ "$TSH_MFA_MODE" = "passwordless" ]]; then
        tsh status &>/dev/null || tsh login --proxy=$TSH_PROXY --user=$TSH_USER --auth=passwordless
    else
        tsh status &>/dev/null || tsh login --proxy=$TSH_PROXY --user=$TSH_USER --mfa-mode=$TSH_MFA_MODE
    fi

}

function tsh_clusters() {
    tsh ls | tail -n +3 | cut -d " " -f 1 | awk NF | sed "s/^/$TSH_SSH_USER\@/"
}


tsh_login

function tsh_ssh() {
    if (( ${+TSH_SSH_USER} )); then
        local cluster=$(tsh_clusters | fzf)
        if ! [ -z "$cluster" ] ; then
            tsh ssh $cluster
        fi
    else
        echo 'Please export TSH_SSH_USER=USERNAME in ~/.zsh-additional-rc'
    fi
}

case "$1" in
    clusters)
        tsh_clusters ;;
    *)
        tsh_ssh
        ;;
esac
