#!/usr/bin/env zsh

set -e

# Set ~/.zsh-additional-rc with
#
# ---- Common configs ---------------------------------------------
#
# export TSH_SSH_USER=toggle
#
# ---- MFA - Passwordless ---------------------------------------------
#
# export TSH_MFA_MODE=passwordless
# export TSH_PROXY=tsh.example.com:443
# export TSH_USER=thenav56
#
# ---- MFA - OPT: Without 1password ---------------------------------------------
#
# export TSH_MFA_MODE=otp
# export OP_TSH_USE='false'
# export TSH_PROXY=tsh.example.com:443
# export TSH_USER=thenav56
#
# ---- MFA - OPT: With 1password ---------------------------------------------
#
# export TSH_MFA_MODE=otp
# export OP_TSH_USE='true'
# export OP_TSH_PROXY='op://Work/Teleport/proxy'
# export OP_TSH_USER='op://Work/Teleport/username'
# export OP_TSH_PASS='op://Work/Teleport/password'
# export OP_TSH_OTP='op://Work/Teleport/one-time password?attribute=otp'
#


_1PASSWORD_COMMAND="$(cat <<'EOF'
set USERNAME $env(OP_TSH_USER)
spawn tsh login --proxy "$env(OP_TSH_PROXY)" --user "$USERNAME" --mfa-mode=otp
expect "Enter password for Teleport user $USERNAME:"
send -- "$env(OP_TSH_PASS)\n"
expect "Enter an OTP code from a device:"
send -- "$env(OP_TSH_OTP)\n"
expect eof
EOF
        )"

# ---- 1password ---------------------------------------------

function tsh_login() {

    if [[ "$TSH_MFA_MODE" = "passwordless" ]]; then
        tsh status &>/dev/null || {
            tsh login --proxy=$TSH_PROXY --user=$TSH_USER --auth=passwordless
        }

    else
        if [[ "$OP_TSH_USE" = "true" ]]; then
            tsh status &>/dev/null || {
                op run -- expect -c "$_1PASSWORD_COMMAND"
            }
        else
            tsh status &>/dev/null || {
                tsh login --proxy "$TSH_PROXY" --user "$TSH_USER" --mfa-mode otp
            }
        fi
    fi

}

function tsh_clusters() {
    tsh ls | tail -n +3 | cut -d " " -f 1 | awk NF | sed "s/^/$TSH_SSH_USER\@/"
}


tsh_login

function tsh_ssh() {
    if (( ${+TSH_SSH_USER} )); then
        local cluster=$(tsh_clusters | fzf)
        if ! [ -z "$cluster" ] ; then
            tsh ssh $cluster
        fi
    else
        echo 'Please export TSH_SSH_USER=USERNAME in ~/.zsh-additional-rc'
    fi
}

case "$1" in
    clusters)
        tsh_clusters ;;
    *)
        tsh_ssh
        ;;
esac
