#!/usr/bin/env bash


function primary_profile {
    xrandr \
        --output HDMI-1 \
            --primary \
            --mode 1920x1080 \
            --pos 1080x370 \
            --rotate normal \
        --output HDMI-2 --off \
        --output DP-2 --off
}

function set_custom_res_mode {
    PROFILE_CODE=$(cvt -v $1 $2 60 | grep Modeline | cut -c 11- | cut -d'"' -f 1)
    if [[ $(xrandr -d $DISPLAY | grep "$PROFILE_CODE" | wc -l) == 0 ]]; then
        echo 'Generating new mode'
        cvt -v $1 $2 60 | grep Modeline | cut -c 10- | xargs xrandr --newmode
        xrandr --addmode HDMI-1 "$PROFILE_CODE"
    fi
    xrandr \
        --output HDMI-1 \
            --mode "$PROFILE_CODE" \
            --pos 0x0 \
        --output HDMI-2 --off \
        --output DP-2 --off
}

function remove_custom_res_mode {
    PROFILE_CODE=$(cvt -v $1 $2 60 | grep Modeline | cut -c 11- | cut -d'"' -f 1)
    if [[ $(xrandr -d $DISPLAY | grep "$PROFILE_CODE" | wc -l) == 0 ]]; then
        echo 'Removing new mode'
        xrandr --delmode HDMI-1 "$PROFILE_CODE"
        xrandr --rmmode "$PROFILE_CODE"
    fi
}

function mac_vnc_profile {
    set_custom_res_mode 1712 1075
}


function all_profile {
    xrandr \
        --output HDMI-2 \
            --mode 1920x1080 \
            --pos 0x30 \
            --rotate left \
        --output HDMI-1 \
            --primary \
            --mode 1920x1080 \
            --pos 1080x370 \
            --rotate normal \
        --output DP-2 \
            --mode 1920x1080 \
            --pos 3000x0 \
            --rotate right
}


function show_usage {
    echo "Usage: $0 <Profile>"
    echo "Profiles:"
    echo "  primary"
    echo "  all"
}


case "$1" in
    primary)
        primary_profile ;;
    mac)
        mac_vnc_profile ;;
    all)
        all_profile ;;
    *)
        show_usage
        exit 1
        ;;
esac

sleep 1
~/.dotfiles/config/polybar/launch_polybar.sh &>/dev/null &
