#!/usr/bin/env bash

set -xe

# Use $HOME/.zsh-additional-rc to define this
if [ -z "$NAV_MACHINE_MAC" ]; then
    echo "NAV_MACHINE_MAC needs to be defined"
    exit 1
fi
if [ -z "$NAV_MACHINE_SSH_HOST" ]; then
    echo "NAV_MACHINE_SSH_HOST needs to be defined"
    exit 1
fi

wakeonlan $NAV_MACHINE_MAC
# ssh -t tc-intel-nuc "wakeonlan $NAV_MACHINE_MAC"

DESKTOP=${1:-i3}


# Check connection and start multiplexer
ssh $NAV_MACHINE_SSH_HOST -t 'whoami'

if [[ "$DESKTOP" == "i3" ]] ; then
    ssh -L localhost:5900:localhost:5900 -t $NAV_MACHINE_SSH_HOST-dot 'DISPLAY=:0 x0vncserver -localhost -SecurityTypes none'
else
    ssh \
        $NAV_MACHINE_SSH_HOST \
        -L localhost:5900:localhost:5900 \
        -t '~/.local/bin/wake-up-for-vnc.sh; WAYLAND_DISPLAY=wayland-1 wayvnc -o HDMI-A-1 -r -k us -L debug --verbose'
fi
