#!/usr/bin/env bash


xrandr \
    --output HDMI-2 \
        --mode 1920x1080 \
        --pos 0x30 \
        --rotate left \
    --output HDMI-1 \
        --primary \
        --mode 1920x1080 \
        --pos 1080x370 \
        --rotate normal \
    --output DP-2 \
        --mode 1920x1080 \
        --pos 3000x0 \
        --rotate right

sleep 1
~/.dotfiles/config/polybar/launch_polybar.sh &
