#!/usr/bin/env bash

DOT_COMMANDS_DIR='~/.dotfiles/commands'

function remote_wol {
    if [ -z "$REMOTE_MACHINE_SSH_WOL_HOST" ]; then
        echo "REMOTE_MACHINE_SSH_WOL_HOST needs to be defined"
        exit 1
    fi
    ssh $REMOTE_MACHINE_SSH_WOL_HOST
}

function remote_vnc_connect {
    set -xe

    # Use $HOME/.zsh-additional-rc to define this
    if [ -z "$REMOTE_MACHINE_SSH_HOST" ]; then
        echo "REMOTE_MACHINE_SSH_HOST needs to be defined"
        exit 1
    fi
    if [ "$REMOTE_MACHINE_SSH_WOL_HOST" ]; then
        echo "Trying to wake-up using ssh host: $REMOTE_MACHINE_SSH_WOL_HOST"
        ssh $REMOTE_MACHINE_SSH_WOL_HOST
    else
        echo "Skip wake-on-lan"
    fi

    DESKTOP=${2:-i3}
    REMOTE_MACHINE_DISPLAY=${REMOTE_MACHINE_DISPLAY:-0}

    # Check connection and start multiplexer if used or just make sure remote is reachable
    ssh $REMOTE_MACHINE_SSH_HOST -t 'whoami'
    # Use primary display profile
    ssh $REMOTE_MACHINE_SSH_HOST -t "DISPLAY=:$REMOTE_MACHINE_DISPLAY $DOT_COMMANDS_DIR/display-profile primary" || true
    ssh $REMOTE_MACHINE_SSH_HOST -t "pkill -9 x0vncserver" || true
    ssh $REMOTE_MACHINE_SSH_HOST -t "$DOT_COMMANDS_DIR/monitor-cmd turn-all-off" || true

    if [[ "$DESKTOP" == "i3" ]] ; then
        ssh -L localhost:5900:localhost:5900 $REMOTE_MACHINE_SSH_HOST -t "DISPLAY=:$REMOTE_MACHINE_DISPLAY x0vncserver -localhost -SecurityTypes none"
        # ssh -L localhost:5900:localhost:5900 $REMOTE_MACHINE_SSH_HOST -t "x11vnc -xkb -localhost -display :$REMOTE_MACHINE_DISPLAY"
    else
        echo 'TODO:'
        # ssh \
        #     $REMOTE_MACHINE_SSH_HOST \
        #     -L localhost:5900:localhost:5900 \
        #     -t '~/.local/bin/wake-up-for-vnc.sh; WAYLAND_DISPLAY=wayland-1 wayvnc -o HDMI-A-1 -r -k us -L debug --verbose'
    fi
    ssh -O exit $REMOTE_MACHINE_SSH_HOST
    set +xe
}

function remote_suspend {
    ssh $REMOTE_MACHINE_SSH_HOST -t "$DOT_COMMANDS_DIR/system-suspend"
    ssh -O exit $REMOTE_MACHINE_SSH_HOST
}


function remote_turn_off_display {
    ssh $REMOTE_MACHINE_SSH_HOST -t "$DOT_COMMANDS_DIR/turn-off-displays"
}

function show_usage {
    echo "Usage: $0 <COMMAND>"
    echo "Commands:"
    echo -e "  wol               -- To wake up your remote system"
    echo -e "  vnc               -- To tunnel remote vnc port to your localhost - 5900"
    echo -e "  turn-off-displays -- To turn off remote display"
    echo -e "  suspend           -- To system remote system"
}


case "$1" in
    vnc)
        remote_vnc_connect ;;
    wol)
        remote_wol ;;
    suspend)
        remote_suspend ;;
    turn-off-displays)
        remote_turn_off_display ;;
    *)
        show_usage
        exit 1
        ;;
esac
