#!/bin/bash

# Turn off all the display
echo "Powering-off all monitors"
~/.dotfiles/commands/monitor-cmd turn-all-off

echo "Suspending now....."
# Without sudo
# https://wiki.archlinux.org/title/Polkit
systemctl --no-ask-password suspend &>/dev/null && exit 0


# With sudo
REQUIRE_PASSWOR_IN_SUDO=$(SUDO_ASKPASS=/bin/false sudo -A systemctl suspend 2>&1 | wc -l)

if [ $REQUIRE_PASSWOR_IN_SUDO = 2 ]; then
    echo "$USER ALL=(ALL:ALL) NOPASSWD: /usr/bin/systemctl suspend" | sudo tee -a /etc/sudoers.d/suspend
else
    exit 0
fi

sudo systemctl suspend
