---
# GRUB Setup -----------------------------------------------------------------
- name: Install Grub
  community.general.pacman:
    name:
      - grub
      - efibootmgr

- name: Grub bootloader install
  ansible.builtin.command: |
    grub-install \
      --target=x86_64-efi \
      --efi-directory=/boot/ \
      --bootloader-id=GRUB
  notify: regenerate grub config

- name: Update grub timeout to 1
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_TIMEOUT=5$'
    line: 'GRUB_TIMEOUT=1'
  notify: regenerate grub config
