---
# GRUB Setup -----------------------------------------------------------------
- name: Install Grub
  community.general.pacman:
    name:
      - grub
      - efibootmgr

- name: Grub bootloader install
  ansible.builtin.command: |
    grub-install \
      --target=x86_64-efi \
      --efi-directory=/boot/ \
      --bootloader-id=GRUB
  args:
    creates: /boot/EFI/GRUB/grubx64.efi
  check_mode: false
  notify: regenerate grub config

- name: Update grub timeout
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_TIMEOUT='
    line: "GRUB_TIMEOUT={{ grub_timeout }}"
  notify: regenerate grub config
