---
# https://wiki.archlinux.org/title/swap#Swap_file
# https://wiki.archlinux.org/title/Zram
# https://aur.archlinux.org/packages/zramswap
- name: enable zramswap
  ansible.builtin.systemd:
    name: zramswap.service
    enabled: yes

- name: start zramswap
  ansible.builtin.systemd:
    name: zramswap.service
    state: started
  when: start_services | bool

# ---- Disk swap (As fallback)
- name: Check whether "{{ swap_vars.path }}" exists
  register: idCheckSwap
  ansible.builtin.stat:
    path: {{ swap_vars.path }}

- name: Fail it if "{{ swap_vars.path }}" exists
  ansible.builtin.fail:
    msg: Swap file exists
  when: idCheckSwap.stat.exists == true

- name: Create swap file
  ansible.builtin.shell: mkswap -U clear --size {{ swap_vars.size }} --file {{ swap_vars.path }}
  args:
    creates: "{{ swap_vars.path }}"
  check_mode: false

- name: Update /etc/fstab
  ansible.builtin.blockinfile:
    path: /etc/fstab
    state: present
    marker: "# {mark} ANSIBLE MANAGED SWAP BLOCK"
    block: |
      {{ swap_vars.path }} swap swap pri=0,defaults 0 0

- name: Activate the swap file as a swap memory using /etc/fstab
  ansible.builtin.shell: swapon -a
  changed_when: false
  check_mode: false

- name: Define sysctl config
  ansible.builtin.blockinfile:
    path: /etc/sysctl.conf
    state: present
    block: |
      vm.swappiness={{ swap_vars.swappiness }}

- name: Apply new config
  ansible.builtin.shell: sysctl -p
  changed_when: false
  check_mode: false
