---
# System packages
- name: Arch Full Update
  become: true
  community.general.pacman:
    update_cache: yes
    upgrade: yes

# Update pacman local db
- name: pacman -Sy
  community.general.pacman:
    update_cache: true
  tags: [always]

# REFLECTOR TO REGULARLY UPDATE MIRRORLIST
- name: install reflector
  community.general.pacman:
    name:
      - reflector

- name: write reflector configuration file
  ansible.builtin.copy:
    dest: '/etc/xdg/reflector/reflector.conf'
    content: |
      --save /etc/pacman.d/mirrorlist
      --protocol http
      --country {{ reflector_country }}
      --score 20
      --sort rate

- name: enable reflector timer
  ansible.builtin.systemd:
    name: reflector.timer
    enabled: yes

- name: start reflector timer
  ansible.builtin.systemd:
    name: reflector.timer
    state: started
  when: start_services | bool

- name: enable reflector service
  ansible.builtin.systemd:
    name: reflector
    enabled: yes

- name: do initial run of reflector.service
  ansible.builtin.systemd:
    name: reflector
    state: started
  when: start_services | bool

# SYSTEM SETTINGS CHANGES ----------------------------------------------------
- name: Custom pacman config
  ansible.builtin.blockinfile:
    path: /etc/pacman.conf
    state: present
    block: |
      [options]
      Color
      ParallelDownloads = 5

      [multilib]
      Include = /etc/pacman.d/mirrorlist

- name: install paccache
  community.general.pacman:
    name:
      - pacman-contrib

- name: Enable pacman cache clear weekly - Last 3 version per package
  ansible.builtin.systemd:
    name: paccache.timer
    enabled: yes

- name: start paccache timer
  ansible.builtin.systemd:
    name: paccache.timer
    state: started
  when: start_services | bool

# ARCHLINUX-KEYRING WEEKLY UPDATE  -------------------------------------------
- name: archlinux-keyring - enable weekly update
  ansible.builtin.systemd:
    name: archlinux-keyring-wkd-sync.timer
    enabled: yes

- name: archlinux-keyring - start weekly update timer
  ansible.builtin.systemd:
    name: archlinux-keyring-wkd-sync.timer
    state: started
  when: start_services | bool
