---
- name: Create /etc/systemd/resolved.conf.d directory if it does not exist
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    state: directory

# DNS configurations - https://wiki.archlinux.org/title/systemd-resolved
- name: systemd-resolved - DNS over TLS
  ansible.builtin.copy:
    dest: /etc/systemd/resolved.conf.d/dns_over_tls.conf
    content: |
      [Resolve]
      DNS={{ dns_servers | join(' ') }}
      DNSOverTLS=yes
  notify: restart systemd-resolved

- name: systemd-resolved - Create a symbolic link for /etc/resolv.conf
  ansible.builtin.file:
    src: ../run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    force: yes
    state: link
    # owner: root
    # group: root

- name: systemd-resolved - enable and start systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    enabled: yes
    state: started
