if [[ -n "$ZSH_DEBUGRC" ]]; then
  zmodload zsh/zprof
fi


### Added by Zinit's installer
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi

# Load brew if in mac
if [[ "$OSTYPE" == "darwin"* ]]; then
    [ -s "/opt/homebrew/bin/brew" ] \
        && eval "$(/opt/homebrew/bin/brew shellenv)"
    alias head=ghead  # from coreutils
fi


source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"

autoload -Uz _zinit

(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zdharma-continuum/zinit-annex-as-monitor \
    zdharma-continuum/zinit-annex-bin-gem-node \
    zdharma-continuum/zinit-annex-patch-dl \
    zdharma-continuum/zinit-annex-rust \
    zdharma-continuum/fast-syntax-highlighting \
    zdharma-continuum/history-search-multi-word \
    zsh-users/zsh-autosuggestions

# Load pure theme
# with zsh-async library that's bundled with it.
zinit ice compile'async.zsh' pick'async.zsh' src'pure.zsh'
zinit light sindresorhus/pure

zinit light-mode for \
    jeffreytse/zsh-vi-mode

zinit \
    atload"zicompinit; zicdreplay" \
    blockf \
    lucid \
    light-mode \
    for \
      wait @zsh-users/zsh-completions \
      wait"0" @"$HOME/.dotfiles/config/zinit/completions"

zinit pack light-mode for ls_colors

export NVM_COMPLETION=true
export NVM_SYMLINK_CURRENT="true"
export NVM_AUTO_USE=true
export NVM_LAZY_LOAD=true

zinit wait lucid light-mode for lukechilds/zsh-nvm

### End of Zinit's installer chunk

# History Configuration
HISTSIZE=10000000
SAVEHIST=10000000
HISTFILE="$HOME/.zsh_history"

setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.

# Environment variables
# Environment variables
CUSTOM_PATHS=(
  "$HOME/go/bin/"
  "$HOME/.local/bin"
  "$HOME/.dotfiles/commands"
  "$HOME/.bun/bin"
  "${KREW_ROOT:-$HOME/.krew}/bin"
  "$HOME/.kube/custom-plugins"
  "$HOME/.cargo/bin"
  "$PATH"
)
export PATH="${(j.:.)CUSTOM_PATHS}"

export EDITOR=nvim
export ZVM_VI_EDITOR=$EDITOR
export VISUAL=$EDITOR
export RIPGREP_CONFIG_PATH=$HOME/.ripgreprc
export DOCKER_BUILDKIT=1
export COMPOSE_BAKE=true
export COMPOSE_DOCKER_CLI_BUILD=1
export HOMEBREW_BUNDLE_FILE="$HOME/.dotfiles/system-packages/brew/brew.Brewfile"

export GPG_TTY=$(tty)
gpgconf --launch gpg-agent

# MANUAL using bat
export MANROFFOPT="-c"
export MANPAGER="nvim +Man!"
export TERM=screen-256color

alias ls="lsd"  # NOTE: use `command ls ..args` for vanilla ls
alias watch="viddy"
alias ssh="TERM=xterm ssh"
alias cat="custom_cat"  # NOTE: use `command cat ..args` for vanilla cat
alias ll='lsd -la --git'
alias srsync="rsync --stats --numeric-ids --info=progress2 -avxhHAX -s"
alias ssrsync="rsync --info=progress2 -axhHAX"
# Zoxide NOTE: zi conflicts with zinit zi, so using custom zii for interactive
alias z="__zoxide_z"
alias zii="__zoxide_zi"

alias k="kubectl"
alias ku="kubie"

# The plugin will auto execute this zvm_after_init function
# NOTE: Call this manually if zsh-vi-mode is not used
function zvm_after_init() {
    # this would bind ctrl + space to accept the current suggestion.
    bindkey '^ ' autosuggest-accept

    # For tsh
    bindkey -s '^f' "_tsh_ssh\n"

    # From tools/fzf-git/fzf-git.sh
    zvm_bindkey viins "^P" up-line-or-beginning-search
    zvm_bindkey viins "^N" down-line-or-beginning-search
    for o in files branches tags remotes hashes stashes lreflogs each_ref; do
        eval "zvm_bindkey viins '^g^${o[1]}' fzf-git-$o-widget"
        eval "zvm_bindkey viins '^g${o[1]}' fzf-git-$o-widget"
    done
}

function custom_cat {
    # Get active theme
    BAT_ACTIVE_THEME=$(command cat $BAT_THEME_VALUE_FILE)
    bat --theme $BAT_ACTIVE_THEME $@
}

function grebase() {
    # Experimental
    BASE_BRANCH=$1
    git checkout $BASE_BRANCH && git pull && git checkout - && git rebase $BASE_BRANCH
}

function gitd() {
    if [[ "$@" =~ "^diff.*" ]]; then
        GIT_EXTERNAL_DIFF=difft git $@
    else
        GIT_EXTERNAL_DIFF=difft git $@ --ext-diff
    fi
}

# Theme
# NOTE: Change using export GTK_DAY_THEME="Awesome-theme" in ~/.zsh-additional-rc
export GTK_DAY_THEME="Arc"
export GTK_NIGHT_THEME="Arc-Dark"
export GIT_DAY_THEME="gruvbox-light"
export GIT_NIGHT_THEME="gruvbox-dark"
export BASE16_DAY_THEME="base16_gruvbox-light-hard"
export BASE16_NIGHT_THEME="base16_gruvbox-dark-soft"
export VIM_DAY_THEME="base16-gruvbox-light-hard"
export VIM_NIGHT_THEME="base16-gruvbox-dark-soft"
export BAT_DAY_THEME="OneHalfLight"
export BAT_NIGHT_THEME="OneHalfDark"

if [[ "$OSTYPE" == "darwin"* ]]; then
    RPROMPT='%F{cyan}%t < '
    export KITTY_DAY_FONT="CaskaydiaCove Nerd Font Mono"
    export KITTY_NIGHT_FONT="CaskaydiaCove Nerd Font Mono Light"
else
    RPROMPT='%F{cyan}%t'
    export KITTY_DAY_FONT="CaskaydiaCove NF"
    export KITTY_NIGHT_FONT="CaskaydiaCove NF Light"
fi

# -- Functions
function linux_system_theme_change(){
    if [[ "$XDG_SESSION_TYPE" == "x11" ]]; then
        echo 'Changing using xsettingsd'
        # Run xsettingsd if not already
        systemctl is-active --user --quiet xsettingsd ||\
            systemctl enable --now --user --quiet xsettingsd.service
        sed -i "s/.*Net\/ThemeName.*/Net\/ThemeName \""$1\""/" ~/.config/xsettingsd/xsettingsd.conf
        killall -HUP xsettingsd
    elif [[ "$XDG_SESSION_TYPE" == "wayland" ]]; then
        echo 'Changing using gsettings'
        eval "gsettings set org.gnome.desktop.interface gtk-theme $1"
    else
        echo "Unknown display server: $XDG_SESSION_TYPE"
    fi
}

function day(){
    # NOTE: gtk not working
    export KITTY_CUSTOM_FONT=$KITTY_DAY_FONT
    export VIM_ACTIVE_THEME=$VIM_DAY_THEME
    eval "$BASE16_DAY_THEME"
    eval "git config --file ~/.git-additional.config delta.light true"
    eval "git config --file ~/.git-additional.config delta.syntax-theme $GIT_DAY_THEME"
    echo "Update $BAT_THEME_VALUE_FILE with $BAT_DAY_THEME"
    echo $BAT_DAY_THEME > $BAT_THEME_VALUE_FILE
    if [[ "$OSTYPE" == "darwin"* ]]; then
        osascript -e 'tell app "System Events" to tell appearance preferences to set dark mode to false'
    else
        linux_system_theme_change $GTK_DAY_THEME
        gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
    fi
}

function night(){
    # NOTE: gtk not working
    export KITTY_CUSTOM_FONT=$KITTY_NIGHT_FONT
    export VIM_ACTIVE_THEME=$VIM_NIGHT_THEME
    eval "$BASE16_NIGHT_THEME"
    eval "git config --file ~/.git-additional.config delta.light false"
    eval "git config --file ~/.git-additional.config delta.syntax-theme $GIT_NIGHT_THEME"
    echo "Update $BAT_THEME_VALUE_FILE with $BAT_NIGHT_THEME"
    echo $BAT_NIGHT_THEME > $BAT_THEME_VALUE_FILE
    if [[ "$OSTYPE" == "darwin"* ]]; then
        osascript -e 'tell app "System Events" to tell appearance preferences to set dark mode to true'
    else
        linux_system_theme_change $GTK_NIGHT_THEME
        gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
    fi
}

# -- Base16 Shell
export BASE16_SHELL_HOOKS="$HOME/.dotfiles/base16/shell-hooks"
export BASE16_THEME_VALUE_FILE="$HOME/.bash16_theme_value"
export VIM_ACTIVE_THEME_FILE="$HOME/.vim_active_theme_file"
export BAT_THEME_VALUE_FILE="$HOME/.bat_theme_value"
BASE16_SHELL="$HOME/.dotfiles/base16/shell/"
[ -n "$PS1" ] &&
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && source "$BASE16_SHELL/profile_helper.sh"

[ -f "$HOME/.config/op/plugins.sh" ] && source "$HOME/.config/op/plugins.sh"

# Include sensitive/overwrite configs/env
# export DAILY_JOURNAL_DIR="$HOME/<path>/journals"
# export DAILY_JOURNAL_REPO_DIR="$HOME/<path>/"
ADDITIONAL_ZSH_CONFIGS="$HOME/.zsh-additional-rc"
[ -f "$ADDITIONAL_ZSH_CONFIGS" ] && source "$ADDITIONAL_ZSH_CONFIGS"

if [[ -n "$ZSH_DEBUGRC" ]]; then
    zprof
fi
