---
- name: Archlinux system configuration for AUR tools
  hosts: localhost
  become: true

  vars_prompt:
    - name: username
      prompt: What is your username?
      private: false

  tasks:
    - ansible.builtin.import_role:
        name: display-manager
