---
- name: Archlinux system configuration
  hosts: localhost
  become: true

  vars_prompt:
    - name: username
      prompt: What is your username?
      private: false

  tasks:
    - ansible.builtin.import_role:
        name: network

    - ansible.builtin.import_role:
        name: dns

    - ansible.builtin.import_role:
        name: pacman

    - ansible.builtin.import_role:
        name: security

    - ansible.builtin.import_role:
        name: display-manager

    - ansible.builtin.import_role:
        name: maintenance

    - ansible.builtin.import_role:
        name: ddcutil

    - ansible.builtin.import_role:
        name: zfs

    - ansible.builtin.import_role:
        name: docker
