---
- name: Archlinux system configuration
  hosts: localhost
  become: true

  vars_prompt:
    - name: username
      prompt: What is your username?
      private: false

  tasks:
    # Network configurations -------------------------------------------------
    - name: systemd-networkd - Wired
      copy:
        dest: /etc/systemd/network/20-wired.network
        content: |
          [Match]
          Name=en*
          [Network]
          DHCP=yes
          [DHCPv4]
          RouteMetric=100
          [IPv6AcceptRA]

    - name: systemd-networkd - Wireless
      copy:
        dest: /etc/systemd/network/25-wireless.network
        content: |
          [Match]
          Name=wlan0
          [Network]
          DHCP=yes
          IgnoreCarrierLoss=3s
          [DHCPv4]
          RouteMetric=200
          [IPv6AcceptRA]
          RouteMetric=200

    - name: enable and start systemd-networkd
      systemd:
        name: systemd-networkd
        enabled: yes
        state: started

    - name: Create /etc/systemd/resolved.conf.d directory if it does not exist
      file:
        path: /etc/systemd/resolved.conf.d
        state: directory

    # DNS configurations - https://wiki.archlinux.org/title/systemd-resolved
    - name: systemd-networkd - Wireless
      copy:
        dest: /etc/systemd/resolved.conf.d/dns_over_tls.conf
        content: |
          [Resolve]
          DNS=1.1.1.1 1.0.0.1
          # DNS=8.8.8.8 8.8.4.4
          DNSOverTLS=yes

    - name: systemd-resolved - Create a symbolic link for /etc/resolv.conf
      ansible.builtin.file:
        src: ../run/systemd/resolve/stub-resolv.conf
        dest: /etc/resolv.conf
        force: yes
        state: link
        # owner: root
        # group: root

    - name: systemd-resolved - enable and start systemd-resolved
      systemd:
        name: systemd-resolved
        enabled: yes
        state: started

    # Update pacman local db
    - name: pacman -Sy
      community.general.pacman:
        update_cache: true
        force: true

    # REFLECTOR TO REGULARLY UPDATE MIRRORLIST
    - name: install reflector
      pacman:
        name:
          - reflector

    - name: write reflector configuration file
      copy:
        dest: '/etc/xdg/reflector/reflector.conf'
        content: |
          --save /etc/pacman.d/mirrorlist
          --protocol http
          --country Singapore
          --score 20
          --sort rate

    - name: enable and start reflector timer
      systemd:
        name: reflector.timer
        enabled: yes
        state: started

    - name: do initial run of reflector.service
      systemd:
        name: reflector
        enabled: yes
        state: started

    # SYSTEM SETTINGS CHANGES ----------------------------------------------------
    - name: Custom pacman config
      blockinfile:
        path: /etc/pacman.conf
        state: present
        block: |
          [options]
          Color
          ParallelDownloads = 5

          [multilib]
          Include = /etc/pacman.d/mirrorlist

    - name: install paccache
      pacman:
        name:
          - pacman-contrib

    - name: Enable pacman cache clear weekly - Last 3 version per package
      systemd:
        name: paccache.timer
        enabled: yes
        state: started

    - ansible.builtin.import_role:
        name: security

    - ansible.builtin.import_role:
        name: display-manager

   # CRONIE  --------------------------------------------------------------------
    - name: install cronie
      pacman:
        name:
          - cronie

    - name: enable and start cronie.service
      systemd:
        name: cronie
        enabled: yes
        state: started

    # ARCHLINUX-KEYRING WEEKLY UPDATE  -------------------------------------------
    - name: archlinux-keyring - enable weekly update
      systemd:
        name: archlinux-keyring-wkd-sync.timer
        enabled: yes
        state: started

    # SSD TRIM SCHEDULED  --------------------------------------------------------
    - name: install util-linux
      pacman:
        name:
          - util-linux

    - name: enable and start weekly ssd disks trim using fstrim timer
      systemd:
        name: fstrim.timer
        enabled: yes
        state: started

    # LOGROTATE  -----------------------------------------------------------------
    - name: install logrotate
      pacman:
        name:
          - logrotate

    - name: logrotate - enable compression
      lineinfile:
        path: /etc/logrotate.conf
        regexp: '^#compress$'
        line: 'compress'

    - name: enable and start daily logs rotation, cleanup
      systemd:
        name: logrotate.timer
        enabled: yes
        state: started

    - ansible.builtin.import_role:
        name: ddcutil

    - ansible.builtin.import_role:
        name: zfs

    # DOCKER SETUP/CONFIGURATION --------------------------------------------------------------
    - name: install docker
      pacman:
        name:
          - docker
          - docker-compose
          - ctop

    - name: add the user to the wheel group
      user:
        name: "{{ username }}"
        groups: docker
        append: yes

    - name: enable docker
      systemd:
        name: docker
        enabled: yes

    - name: Create /etc/docker directory if it does not exist
      file:
        path: /etc/docker
        state: directory
        mode: '0755'

    - name: set default max logs size to 250MB and set logs rotation
      copy:
        dest: '/etc/docker/daemon.json'
        content: |
          {
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "50m",
              "max-file": "5"
            }
          }
