---
- name: Archlinux system packages
  hosts: localhost

  tasks:
    - ansible.builtin.import_role:
        name: pacman-packages

    - name: Install packages with uv tool install
      ansible.builtin.shell: |
        uv tool install --no-progress {{ item }}
      args:
        executable: /bin/bash
        creates: "{{ ansible_env.HOME }}/.local/bin/{{ item }}"
      loop:
        - neovim-remote
        - --with requests ipython
        - django
        - pre-commit
        - flake8
        - isort
        - ruff
        - line-profiler
        - snakeviz
        - --with openpyxl visidata
        - azure-cli
        - --with requests jupyterlab
        - ddcci_plasmoid_backend
