# TODO: Check if this works -----
---
- name: Setup swap
  hosts: localhost
  become: true
  vars:
    swap_vars:
      size: 8G
      path: /swapfile
      swappiness: 60  # Default

  tasks:

    # https://wiki.archlinux.org/title/swap#Swap_file
    # https://wiki.archlinux.org/title/Zram
    # https://aur.archlinux.org/packages/zramswap
    - name: enable zramswap
      systemd:
        name: zramswap.service
        enabled: yes
        state: started

    # ---- Disk swap (As fallback)
    - name: Check whether "{{ swap_vars.path }}" exists
      register: idCheckSwap
      stat:
        path: {{ swap_vars.path }}

    - name: Fail it if "{{ swap_vars.path }}" exists
      fail:
        msg: Swap file exists
      when: idCheckSwap.stat.exists == true

    - name: Create swap file
      shell: mkswap -U clear --size {{ swap_vars.size }} --file {{ swap_vars.path }}

    - name: Update /etc/fstab
      blockinfile:
        path: /etc/fstab
        state: present
        marker: "# {mark} ANSIBLE MANAGED SWAP BLOCK"
        block: |
          {{ swap_vars.path }} swap swap pri=0,defaults 0 0

    - name: Activate the swap file as a swap memory using /etc/fstab
      shell: swapon -a

    - name: Define sysctl config
      blockinfile:
        path: /etc/sysctl.conf
        state: present
        block: |
          vm.swappiness={{ swap_vars.swappiness }}

    - name: Apply new config
      shell: sysctl -p
