include kitty-base.conf

font_family      CaskaydiaCove NF
italic_font      auto
bold_font        auto
bold_italic_font auto

modify_font cell_height 4px
modify_font baseline 0

font_size 10.5
single_window_margin_width 2
single_window_padding_width 2

# Custom overrides - This needs to be called at last
# Disable tab navigation in linux
map ctrl+tab no_op

include base16_hooks.conf
