k9s:
  # Toggles whether k9s should exit when CTRL-C is pressed. When set to true, you will need to exist k9s via the :quit command. Default is false.
  noExitOnCtrlC: true
  logger:
    textWrap: true
  ui:
    skin: transparent
    headless: true
    # skin: solarized-light
