---
# Network configurations -------------------------------------------------
- name: systemd-networkd - Wired
  ansible.builtin.copy:
    dest: /etc/systemd/network/20-wired.network
    content: |
      [Match]
      Name=en*
      [Network]
      DHCP=yes
      [DHCPv4]
      RouteMetric=100
      [IPv6AcceptRA]
  notify: restart systemd-networkd

- name: systemd-networkd - Wireless
  ansible.builtin.copy:
    dest: /etc/systemd/network/25-wireless.network
    content: |
      [Match]
      Name={{ wireless_iface }}
      [Network]
      DHCP=yes
      IgnoreCarrierLoss=3s
      [DHCPv4]
      RouteMetric=200
      [IPv6AcceptRA]
      RouteMetric=200
  notify: restart systemd-networkd

- name: enable systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    enabled: yes

- name: start systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    state: started
  when: start_services | bool

- name: install iwd
  community.general.pacman:
    name:
      - iwd
      - impala

- name: enable iwd
  ansible.builtin.systemd:
    name: iwd
    enabled: yes
